---
- name: "Playbook wrapper for linchpin duffy on fedora atomic"
  hosts: "fedora-atomic.ci.centos.org"
  tasks:
    - name: "generate a runid"
      shell: "python -c 'import time; print(int(time.time()))'"
      register: run_id
    - name: "set runid"
      set_fact:
        run_id: "{{ run_id['stdout'] }}"
    - name: "create a directory"
      file:
        path: "/tmp/linchpin_ws_{{ run_id }}"
        state: directory
    - name: "create a directory for workspace"
      file:
        path: "/tmp/linchpin_ws_{{ run_id }}/workspace"
        state: directory
    - name: "create a virtual env inside directory"
      pip:
        name: setuptools
        virtualenv: "/tmp/linchpin_ws_{{ run_id }}"
        state: latest
    - name: "create a virtual env inside directory"
      pip:
        name: pytz
        virtualenv: "/tmp/linchpin_ws_{{ run_id }}"
        state: latest
    - name: "install linchpin inside the virtula env"
      pip:
        name: linchpin
        virtualenv: "/tmp/linchpin_ws_{{ run_id }}"
        state: latest
    - name: "clone the workspace into the folder"
      git:
        repo: https://github.com/samvarankashyap/linchpin_openshift_e2e.git
        dest: "/tmp/linchpin_ws_{{ run_id }}/workspace"
    #- name: "run the linchpin up on the workspace"
    #- name: "run linchpin destroy on workspace"
    - name: "run linchpin version" 
      command: "~/sk_workspace/venvs/lp_duffy/bin/linchpin --version"
      register: out
    - debug: msg=out
    - name: "run linchpin up to provision duffy node"
      command: "~/sk_workspace/venvs/lp_duffy/bin/linchpin -w /home/fedora-atomic/sk_workspace/lpduffy/linchtest -v up"
      register: out2
    - debug: msg=out2
    - name: "run linchpin drop teardown duffy node"
      command: "~/sk_workspace/venvs/lp_duffy/bin/linchpin -w /home/fedora-atomic/sk_workspace/lpduffy/linchtest -v drop"
      register: out3
    - debug: msg=out3
