---
- name: "Playbook wrapper for linchpin duffy on fedora atomic"
  hosts: all
  tasks:
    - name: "generate a runid"
      shell: "python -c 'import time; print(int(time.time()))'"
      register: run_id
      delegate_to: 127.0.0.1

    - name: "set runid"
      set_fact:
        run_id: "{{ run_id['stdout'] }}"
      delegate_to: 127.0.0.1
    - name: "create a directory"
      file:
        path: "/tmp/linchpin_ws_{{ run_id }}"
        state: directory
      delegate_to: fedora-atomic.ci.centos.org 
        #    - name: "create a directory for workspace"
        #file:
        #path: "/tmp/linchpin_ws_{{ run_id }}/workspace"
        #state: directory
        #  - name: "create a virtual env inside directory"
        #pip:
        #name: setuptools
        #virtualenv: "/tmp/linchpin_ws_{{ run_id }}"
        #state: latest
        #- name: "create a virtual env inside directory"
        #pip:
        #name: pytz
        #virtualenv: "/tmp/linchpin_ws_{{ run_id }}"
        #state: latest
        #- name: "install linchpin inside the virtula env"
        #pip:
        #name: linchpin
        #virtualenv: "/tmp/linchpin_ws_{{ run_id }}"
        #state: latest
        #- name: "clone the workspace into the folder"
        #git:
        #repo: https://github.com/samvarankashyap/linchpin_openshift_e2e.git
        #dest: "/tmp/linchpin_ws_{{ run_id }}/workspace"
    #- name: "run the linchpin up on the workspace"
    #- name: "run linchpin destroy on workspace"
    #- name: "run linchpin version"
    #  command: "~/sk_workspace/venvs/lp_duffy/bin/linchpin --version"
    #  register: out
    #- debug: msg=out
    - name: "run linchpin up to provision duffy node"
      command: "~/sk_workspace2/venvs/lp_duffy/bin/linchpin -w /home/fedora-atomic/sk_workspace2/lpduffy/linchtest -v up"
      async: 7200
      poll: 0
      delegate_to: fedora-atomic.ci.centos.org
      register: run_sleeper

    - name: 'check on fire and forget task'
      async_status: jid={{ run_sleeper.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 120
      delay: 60
      delegate_to: fedora-atomic.ci.centos.org
    - debug: msg=run_sleeper

    - name: "run linchpin drop teardown duffy node"
      command: "~/sk_workspace2/venvs/lp_duffy/bin/linchpin -w /home/fedora-atomic/sk_workspace2/lpduffy/linchtest -v drop"
      register: out3
      delegate_to: fedora-atomic.ci.centos.org

    - debug: msg=out3
    - name: remove e2e.log if exists
      file:
        path: "e2e.log"
        state: absent
      ignore_errors: yes
    - name: fetch the e2e.log file
      fetch:
        src: /tmp/e2e.log
        dest: e2e.log
        flat: yes
      delegate_to: fedora-atomic.ci.centos.org
